### ISSUE TITLE
Include PVC Metrics

### ISSUE THREAD

**Issue by jmcshane** [utilitywarehouse/kube-summary-exporter#19]
PVC metrics are also an issue with the lack of information coming out of the kubelet prom endpoint. Would this library be open to a PR to add these metrics?

**Comment by george-angel** [comment]
Hello!

Could you please elaborate which metrics you are missing (that are present with Docker runtime) that you would like to see added?

**Comment by sidewinder12s** [comment]
I believe I've gotten PVC metrics from kube-state-metrics in the past.

**Comment by george-angel** [comment]
Please let us know if this is still an issue.
