### ISSUE TITLE
Run as DaemonSet?

### ISSUE THREAD

**Issue by sidewinder12s** [utilitywarehouse/kube-summary-exporter#28]
Can this be run as a daemonset in its current state so you do not need to provide the node name to the metrics endpoint call?

**Comment by george-angel** [comment]
Can you tell me more why you would need this?

We have example scrape config here: https://github.com/utilitywarehouse/kube-summary-exporter/blob/master/manifests/scrap-config.yaml

**Comment by sidewinder12s** [comment]
Huh. I have not used some of those relabel rules before. We use a prometheus compatible metrics solution which may not support all the features of relabeling, but I think I can run this as a daemonset with the relabel rules that do work. 

We had other concerns around concentrating the collection of these metrics in 1 exporter on extremely large clusters otherwise (10k+ pods) and figured a DS might perform more consistently.

**Comment by george-angel** [comment]
I see - to address the scaling question - you can increase the replicas of the Deployment to run more to handle the potential load. That would be best case scenario.

If you are unable to relabel - you might have to come up with an alternative strategy for running the exporter. DaemonSet would be one, but its quite an edge case, so you will have to figure out the best way yourself.

**Comment by george-angel** [comment]
Please let us know if this is still an issue.
